export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

import "../styles/globals.css"

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en" className="dark">
      <body className="min-h-screen bg-[#38bdf8] bg-no-repeat bg-fixed">
        {children}
      </body>
    </html>
  )
}
